### ISSUE TITLE
Coda Freezes

### ISSUE THREAD

**Issue by cn-grant** [Ibmurai/Markdown.codaplugin#1]
I'm finished working on a markdown file (.md) and I decide to make it browser compatible.

Plug-ins > Markdown > Convert to HTML, Coda freezes and I'm stuck in rainbow-loading-spinner-hell.

I've re-installed the plug-in multiple times; same problem every time. I've had this plug-in installed for about a month and it's just started doing this yesterday.

**Comment by cn-grant** [comment]
I re-installed the plug-in through the terminal this time and now it works... _grumble_

**Comment by Ibmurai** [comment]
Let me just comment on this: I have experienced the same myself, and found that it only happens with certain Markdown files.
It may be a bug in daringfireball's implementation, but more likely it is due to the way Coda (or I) handle the input to the perl script. 
I will look into it, so I am reopening your issue.

**Comment by cn-grant** [comment]
You know, as you mention this, I discovered yesterday that this is more than likely the case.

I created a fresh markdown file to test and it converted it beautifully.

However, when I re-attempted to convert the problematic file, the same issue still occurred. It's 300+ sloc, so checking the syntax will take a bit of time, if that's the truly problem.

Thanks for re-opening.

**Comment by Ibmurai** [comment]
I just changed the input method to always be the whole document, and that seems to fix it for me.

Let me know how it works for you - If it works, I will tag it ;)

**Comment by cn-grant** [comment]
I'm afraid the issue persists.

**Comment by Ibmurai** [comment]
Bummer. I will look into it.

**Comment by Ibmurai** [comment]
I believe I've fixed it. Try the new master - I will tag it if it works... It does for me ;)

**Comment by cn-grant** [comment]
Well done. The problematic file now converts fine.

Who knew, the wrapping-everything-in-a-php-script technique prevails

**Comment by Ibmurai** [comment]
Yup, it's silly but it works...
