### ISSUE TITLE
coda 2 support?

### ISSUE THREAD

**Issue by pketh** [Ibmurai/Markdown.codaplugin#2]
Does this work with Coda 2? Thinking of upgrading but I really need my markdown :)

thanks!

**Comment by Ibmurai** [comment]
It does not, but conversion is simple. I will convert it come tursday. 
Great to hear someone else is using it :)

If you have any feature requests, ideas or bug reports, please do not hesitate to create more issues.

**Comment by acusti** [comment]
I’m very glad to hear you will be converting it! I am also looking forward to having it Coda 2 compatible. I was considering trying it myself based on [Panic’s instructions](http://panic.com/coda/plugins.php) and making a pull request, but I probably would have made a mess of it and given up. Thanks for the plugin, which has been quite useful for me, and thanks in advance for the update.

**Comment by Ibmurai** [comment]
Fixed.
It was simple enough.
