### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by q0rban** [Ibmurai/Markdown.codaplugin#4]
I followed the git clone installation instructions in the Readme, restarted Coda 2, tried both of the shortcuts on a readme.md file, and nothing happens. Is there a way to troubleshoot this?

**Comment by Ibmurai** [comment]
Not that I know of...
Do the shortcuts appear in the plugins menu? Otherwise you have probably misplaced it...

**Comment by q0rban** [comment]
I had to close coda a second time and reopen it and then it showed. Thanks!

**Comment by Ibmurai** [comment]
Alrighty then! :)
