### ISSUE TITLE
iFrame element causes a new preview window to appear

### ISSUE THREAD

**Issue by willco007** [Ibmurai/Markdown.codaplugin#5]
Reported from a Coda user: When I edit an HTML file that contains an iframe with a src attribute that starts with "http:", whenever a key is pressed, a new preview browser window with what I have typed in the attribute will appear.

This is a bug in this plugin that needs to be fixed.

**Comment by Ibmurai** [comment]
That sounds really funky... Just to confirm: You are using the latest version of Coda 2, right?

I'll look into it, asap...

**Comment by willco007** [comment]
Yes, this has been reported numerous times by our users (I am a developer of Coda if you didn't notice). :)  Thanks for looking into this.

**Comment by Ibmurai** [comment]
``` html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <iframe src="http://google.com"></iframe>
</body>
```

I cannot reproduce, with the code above... Can you give me an example of an html file that causes this?

**Comment by willco007** [comment]
Oh boy, I just realized it was a _different_ mark-down plugin causing the issue.  Terribly sorry about that. :\

**Comment by willco007** [comment]
Type this:

<iframe src="http://www.google.com"
Then type ">".  As soon as you type > the plug-in will open a tab in your default browser (I thought it was in Coda, but it wasn't passed on clearly to me).
Thanks,
Will

**Comment by Ibmurai** [comment]
Then I will close this non-issue :)
